# Contents of this file are appended to the end of the autogenerated 
# edf2py.py script.

import os
import ctypes as ct

def edf_file(file_name):
    error_code = ct.c_int(1)
    file_path=os.path.normpath(os.path.abspath(file_name))
    edf_ptr = open_file(file_path, 2, 1, 1, ct.byref(error_code))
    if edf_ptr is None or error_code.value != 0:
        return None
    return edf_ptr
    
def preamble_text(edfptr):
    preambleText = String()
    tlen = get_preamble_text_length(edfptr)
    get_preamble_text(edfptr, preambleText, tlen+1)
    return preambleText
    
import defines
from defines import edf_constants as constants
from defines import event_constants as event_constants
from defines import eye_constants as eye_constants

